### ISSUE TITLE
[Question] how to MinVer? 

### ISSUE THREAD

**Issue by CatsArmy** [Distractic/LethalCompanyTemplate#21]
I tried setting up  custom Platforms that copy the AnyCPU platform to select whether this build should increment the patch/minor/major version of the package.

Then I realized that MinVer isn't doing anything for me and so I searched (alot) and found nothing so thought I'd ask here for a wiki/totourial on how to use the minver

**Comment by CatsArmy** [comment]
I tried looking Into how it works closest thing I found was something about the git tags which had no examples on how it worked

**Comment by Computerdores** [comment]
I am not sure, but I don't think it is used at all.

The CI/CD pipeline uses [Googles Release Please Action](https://github.com/google-github-actions/release-please-action?tab=readme-ov-file) which determines the version according to [Conventional Commit messages](https://www.conventionalcommits.org/). 
Whenever you push commits according to that convention it will create/update a pull request for a new release, once you merge that pull request it will automatically create a new github release and upload the new version to Thunderstore (assuming you have set everything up correctly).

That said MinVer shows up in some files and I don't know why (My theory is that it is a vestigial artifact from earlier versions of the Template).
